version: "3"

services:
  mynginx:
    build: ../myngin
    image: mynginx
    container_name: mynginx-container
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
    restart: unless-stopped
